Add protokoll
datasektionen/bawang-content pull request #196
Opened 2021-11-05 14:24 UTC by christian-stj

2021-11-05 14:43 UTC, elmaxe requested changes

2021-11-05 14:43 UTC, elmaxe commented on en/organisation/protokoll/body.md
> +29/10 DM-before-Budget-CM ([action minutes](yoggi.datasektionen.se/beslutsprotokoll/dm_innan_budget_sm_2021))
```suggestion
29/10 DM-before-Budget-CM ([action minutes](https://yoggi.datasektionen.se/beslutsprotokoll/dm_innan_budget_sm_2021))
```

2021-11-05 14:43 UTC, elmaxe commented on en/organisation/protokoll/body.md
> +6/10 An-eased-DM ([action minutes](yoggi.datasektionen.se/beslutsprotokoll/ett_lattat_dm_2021))
```suggestion
6/10 An-eased-DM ([action minutes](https://yoggi.datasektionen.se/beslutsprotokoll/ett_lattat_dm_2021))
```

2021-11-05 14:43 UTC, elmaxe commented on organisation/protokoll/body.md
> +6/10 Ett-lättat-DM ([beslutsprotokoll](yoggi.datasektionen.se/beslutsprotokoll/ett_lattat_dm_2021))
```suggestion
6/10 Ett-lättat-DM ([beslutsprotokoll](https://yoggi.datasektionen.se/beslutsprotokoll/ett_lattat_dm_2021))
```

2021-11-05 14:44 UTC, elmaxe commented on organisation/protokoll/body.md
> +29/10 DM-innan-Budget-SM ([beslutsprotokoll](yoggi.datasektionen.se/beslutsprotokoll/dm_innan_budget_sm_2021))
```suggestion
29/10 DM-innan-Budget-SM ([beslutsprotokoll](https://yoggi.datasektionen.se/beslutsprotokoll/dm_innan_budget_sm_2021))
```

2021-11-07 10:55 UTC, triggerdude33 approved these changes
Looks good.

2021-11-07 18:38 UTC, elmaxe approved these changes

2021-11-07 18:38 UTC, merged