Added mail addresses to drek positions in descriptions
datasektionen/bawang-content pull request #223
Opened 2021-12-15 20:08 UTC by NilssonWilliam

2021-12-16 11:19 UTC, elmaxe commented
#181

2021-12-23 16:55 UTC, Grunler requested changes

2021-12-23 16:55 UTC, Grunler commented on organisation/sammansattning/body.md
> +Ledamot för näringsliv och kommunikation frågor är nåbar på d-nok@d.kth.se
```suggestion
Ledamot för näringsliv och kommunikation är nåbar på d-nok@d.kth.se
```

2021-12-31 23:50 UTC, MalinSvenberg approved these changes
Sgtm 😊

2022-01-02 17:44 UTC, Grunler approved these changes

2022-01-02 17:45 UTC, Grunler commented
lgtm

2022-01-02 17:46 UTC, merged

2022-01-07 14:29 UTC, oskstr commented
Shouldn't the email addresses perhaps have the format: 
```markdown
[ordf@d.kth.se](mailto:ordf@d.kth.se)
```
to be a link that opens in an email client like we have in other places? like here [kontakt/body.md](https://github.com/datasektionen/bawang-content/blob/master/kontakt/body.md)