Uppdatering beskrivning Valberedningen
datasektionen/bawang-content pull request #293
Opened 2022-04-25 16:57 UTC by Blytungdev

Uppdatering av den svenska sidan samt skapande av den engelska

## Describe your changes
Skrev en bättre beskrivning och upptäckte det engelska språket
## Checklist before requesting a review

- [x] I have performed a self-review of my changes
- [x] I have updated both Swedish and English pages (if not motivate why)

2022-04-25 16:58 UTC, Blytungdev commented
@niklasvatn @elmaxe

2022-04-25 23:22 UTC, Herkarl requested changes
Suggested adjustment of translation of valberedning according to previous conversation

2022-04-25 23:22 UTC, Herkarl commented on en/clubs/Valberedningen/body.md
> +# Nominating Committee (Valberedningen)
```suggestion
# Election Committee (Valberedningen)
```

2022-04-25 23:22 UTC, Herkarl commented on en/clubs/Valberedningen/body.md
> +The Nominating Committee administrates elections within the chapter and arranges the Chapter Fair once per semester. The Nominating Committee usually consists of 6 Committee members and [The Chairper
```suggestion
The Election Committee administrates elections within the chapter and arranges the Chapter Fair once per semester. The Election Committee usually consists of 6 Committee members and [The Chairperson](https://dfunkt.datasektionen.se/position/id/34/).
```

2022-04-25 23:22 UTC, Herkarl commented on en/clubs/Valberedningen/body.md
> +# Nominating Committee (Valberedningen)
```suggestion
# Election Committee (Valberedningen)
```

2022-04-25 23:22 UTC, Herkarl commented on en/clubs/Valberedningen/body.md
> +Ahead of each election the Nominating Committee opens nominations for posts at [val.datasektionen.se](https://val.datasektionen.se/). Those nominated can then either accept or decline their nominatio
```suggestion
Ahead of each election the Election Committee opens nominations for posts at [val.datasektionen.se](https://val.datasektionen.se/). Those nominated can then either accept or decline their nominations. When a candidate accepts their nomination the Election Committee will invite the candidate to an interview. Based on the interview, a written statement will be produced which the candidate can correct any errors in. Thereafter the Election Committee will make a judgement on whether the candidate is suitable for the post. All statements and judgements will be published in the election documents for the Chapter Meeting to review.
```

2022-04-25 23:22 UTC, Herkarl commented on en/clubs/Valberedningen/body.md
> +Once per semester the Nominating Committee arranges the Chapter Fair. At the Fair, chapter officials, committees and projects present their activities to the chapter members. There might also be a pa
```suggestion
Once per semester the Election Committee arranges the Chapter Fair. At the Fair, chapter officials, committees and projects present their activities to the chapter members. There might also be a patch for those deemed worthy. 
```

2022-04-25 23:22 UTC, Herkarl commented on en/clubs/Valberedningen/sidebar.md
> +#### Nominating Committee Chairperson
```suggestion
#### Election Committee Chairperson
```

2022-04-25 23:35 UTC, Herkarl requested changes
Otherwise lgtm

2022-04-25 23:35 UTC, Herkarl commented on en/clubs/Valberedningen/sidebar.md
> +[valberedning@d.kth.se](mailto:valberedning@d.kth.se)
This email should be [valberedning-ordf@d.kth.se](mailto:valberedning-ordf@d.kth.se)

[valberedning@d.kth.se](mailto:valberedning@d.kth.se) should probably still be included, perhaps just below ## Contact?

Same comments apply to Swedish page

2022-04-25 23:40 UTC, Herkarl commented
@Blytungdev @lucubrator

2022-04-27 08:12 UTC, Herkarl approved these changes

2022-04-27 08:13 UTC, merged