Uppdaterade klubbmästarordern
datasektionen/bawang-content pull request #345
Opened 2022-09-26 12:28 UTC by DowLucas

2022-09-26 14:11 UTC, Dpuu requested changes
Missing English update

2022-09-26 21:54 UTC, DowLucas commented
> Missing English update

Done! 👍🏼

2022-10-15 16:31 UTC, Herkarl approved these changes

2022-10-15 16:34 UTC, Herkarl commented
@Dpuu Merging is blocked until you make an approving review.

2022-10-16 14:55 UTC, merged