Translate JN
datasektionen/bawang-content pull request #366
Opened 2022-11-01 08:33 UTC by laurani02

Pontus, du var för snabb

## Describe your changes
Översatts JN:s text
## Checklist before requesting a review

- [x] I have performed a self-review of my changes
- [x] I have updated both Swedish and English pages (if not motivate why)

2022-11-01 08:34 UTC, psoder commented
:)

2022-11-01 08:40 UTC, Herkarl approved these changes
Could perhaps have a link to [jml.datasektionen.se](https://jml.datasektionen.se). Although that page is only in Swedish, so it's fair not to.

Otherwise lgtm

2022-11-01 08:40 UTC, psoder commented on en/clubs/jamlikhetsnamnden/body.md
> +In the first place, you can contact the committee by emailing [the head of the Equality Board](mailto:jno@datasektionen.se).
"The easiest way to get in touch" är känns som en bättre formulering?

2022-11-01 08:41 UTC, psoder commented on en/clubs/jamlikhetsnamnden/body.md
> +If you discover something that you think is wrong, offensive or discriminates against any person or group, you should talk to us. It can be anything from a teacher saying inappropriate things in a le
I
> in a lecture, to a student

tror jag inte att det ska vara något ",".

2022-11-01 08:42 UTC, psoder commented on en/clubs/jamlikhetsnamnden/body.md
> +You can also email the head of the committee if you want to join.
Det här stycket säger väl i princip samma sak som,

> In the first place, you can contact the committee by emailing [the head of the Equality Board](mailto:jno@datasektionen.se).

2022-11-01 08:44 UTC, psoder requested changes

2022-11-01 08:44 UTC, psoder commented on en/clubs/jamlikhetsnamnden/body.md
> +You can also email the head of the committee if you want to join.
Det här stycket säger väl i princip samma sak som,

> In the first place, you can contact the committee by emailing [the head of the Equality Board](mailto:jno@datasektionen.se).

2022-11-01 08:44 UTC, psoder commented on en/clubs/jamlikhetsnamnden/body.md
> +If you discover something that you think is wrong, offensive or discriminates against any person or group, you should talk to us. It can be anything from a teacher saying inappropriate things in a le
I
> in a lecture, to a student

tror jag inte att det ska vara något ",".

2022-11-01 08:44 UTC, psoder commented on en/clubs/jamlikhetsnamnden/body.md
> +In the first place, you can contact the committee by emailing [the head of the Equality Board](mailto:jno@datasektionen.se).
"The easiest way to get in touch" är känns som en bättre formulering?

2022-11-05 19:09 UTC, laurani02 commented
Har uppdaterat nu :)

2022-11-06 00:33 UTC, psoder approved these changes
lgtm

2022-11-06 00:34 UTC, merged