Lallstedters patch 1
datasektionen/bawang-content pull request #377
Opened 2022-11-24 09:24 UTC by lallstedters

## Describe your changes

Updated info for Adas page, including relevant names and contact info.

## Checklist before requesting a review

- [ x] I have performed a self-review of my changes
- [x ] I have updated both Swedish and English pages (if not motivate why)

2022-11-24 11:50 UTC, Herkarl requested changes
Liten formateringssak, men annars LGTM

2022-11-24 11:50 UTC, Herkarl commented on en/clubs/geek/body.md
> +**Ada 22/23*
```suggestion
**Ada 22/23**
```

2022-11-24 11:50 UTC, Herkarl commented on en/clubs/geek/body.md
>  **Ada 21/22*
```suggestion
**Ada 21/22**
```

2022-11-24 14:46 UTC, elmaxe commented on en/clubs/geek/sidebar.md
> +Head of Ada,
```suggestion<br />
Head of Ada,
```

2022-11-24 14:47 UTC, elmaxe requested changes

2022-11-24 14:47 UTC, elmaxe commented on en/clubs/geek/sidebar.md
> +Klara Sandström
```suggestion
Head of Ada,<br />
Klara Sandström
```

2022-11-28 09:44 UTC, niklasvatn commented
@Herkarl @elmaxe @lallstedters 
I committed the suggested edits.
Merging it would be good. Might want to double-check with the author first though.

2022-11-28 09:48 UTC, lallstedters commented
> 

I'm fine with the changes, thank you for fixing it and sorry for the sloppy work.

2022-11-28 09:52 UTC, elmaxe approved these changes

2022-11-28 10:48 UTC, Herkarl approved these changes

2022-11-28 10:48 UTC, merged