Arrange all committee pages into organs
datasektionen/bawang-content pull request #565
Opened 2024-11-10 23:32 UTC by Benjaneb

## Describe your changes
Since datasektionen/bawang#91 the website fully supports subfolders so it's time to make use of this and arrange all committee pages under their respective organs for easier navigation among the plenty of organs and projects. It's also good to communicate organs being a thing to chapter members through the website.

## Checklist before requesting a review

- [x] I have performed a self-review of my changes
  - Instructions for easily viewing your changes locally is available in [the readme](https://github.com/datasektionen/bawang-content?tab=readme-ov-file#k%C3%B6ra-lokalt).
- [x] I have updated both Swedish and English pages (if not motivate why)

2024-11-11 13:52 UTC, Herkarl requested changes
Nice! Ser mycket mer clean ut nu!
Stämmer vad jag kan se överens med ändringarna från proppen.

Lite saker som jag tycker borde fixas/ändras:
- Mottagninsorganet saknas. Typ fair egentligen iom att det bara är mottagningen som är med där, men tycker det är bättre att vara konsekvent, och för att visa att det är en grej som existerar för gemene sektionsmedlem.
- Vore bra att ha en kort beskrivning av typ vad organ är på `/namnder`. Den behöver inte gå in på vad varje organ är, men typ bara förklara att det är en grej och lite hur de fungerar organisatoriskt.

Noterar också att D-festeriet och D-dagen verkar saknas? Men det ser ju ut att vara en bugg sedan tidigare, och som syns tydligare nu när sidan blir bättre organsierad, så behöver nog inte fixas i den här PRen.

2024-11-11 14:07 UTC, Herkarl commented on namnder/body_sv.md
> +### [Systemgruppen](/namnder/informationsorganet/systemgruppen)
lol, fin diff

2024-11-13 00:06 UTC, Benjaneb commented
>     * Mottagninsorganet saknas som rubrik. Typ fair egentligen iom att det bara är mottagningen som är med där, men tycker det är bättre att vara konsekvent, och för att visa att det är en grej som existerar organisatoriskt för gemene sektionsmedlem.

Jag känner att det hade tagit onödig plats och mottagningsorganet är inte en grej i praktiken, utan bara på papper, så det behöver en extra titel på hemsidan imo.

>     * Vore bra att ha en kort beskrivning av typ vad organ är på `/namnder`. Den behöver inte gå in på vad varje organ är, men typ bara förklara att det är en grej och lite hur de fungerar organisatoriskt.

Bra idé

> Noterar också att D-festeriet och D-dagen verkar saknas? Men det ser ju ut att vara en bugg sedan tidigare, och som syns tydligare nu när sidan blir bättre organsierad, så behöver nog inte fixas i den här PRen.

Yeah de får lägga till sina sidor i egna PRs, har pushat på Roger att göra det ett tag :pensive:.

2024-11-13 11:11 UTC, Herkarl approved these changes
Nice!

2024-11-13 11:15 UTC, Herkarl commented
> Jag känner att det hade tagit onödig plats och mottagningsorganet är inte en grej i praktiken, utan bara på papper, så det behöver en extra titel på hemsidan imo.

Tänkte typ att mottagningens sida blev lite lätt att missa när den bara inte hade en titel och låg längst ned, medans det typ är en av sidorna som (antagligen?) bör får mest trafik, men går nog att lösa på något annat sätt

2024-11-13 12:58 UTC, merged